services:
  db:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
